services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto_broker
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./passwd:/mosquitto/config/passwd
      - ./certs:/mosquitto/config/certs

  mock-pdu:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    volumes:
      - ./certs:/app/certs:ro
      - ./devices_config.json:/app/devices_config.json:ro
    container_name: pdu_simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_TOKEN=${MQTT_TOKEN}
      - MQTT_PORT=${MQTT_PORT}
      - CONFIG_FILE=${CONFIG_FILE}