listener 8883
cafile /run/secrets/ca_cert
certfile /run/secrets/server_cert
keyfile /run/secrets/server_key

# Password and token authentication (TLS & Auth)
allow_anonymous false
password_file /run/secrets/mqtt_passwd
